### ISSUE TITLE
shapes_demo working?

### ISSUE THREAD

**Issue by kczimm** [jhelovuo/RustDDS#1]
Love the project. I hope to contribute.

I ran the shapes demo with `cargo run --example shapes_demo` and nothing happened. Is it functional? I wanted to use it start understanding the crate in case there were opportunities I could help. Thanks in advance.

**Comment by jhelovuo** [comment]
It worked the last time we tried. How did you test?

The shapes demo is supposed to show communication with another DDS implementation, so you need the other participant too, e.g. https://github.com/eProsima/ShapesDemo or try googling for "dds shapes demo download" for other alternatives. So you need to run both the RustDDS example and the other Shapes demo implementation at the same time.

Contributions are welcome! What would you like to do?

**Comment by kczimm** [comment]
Thanks for getting back so quickly. I tried running two instances of the example and both didn't have any output. I'll try running another implementation as you suggest to test it out. 

I don't know where to help. Is there an area in particular that needs work? Is there a roadmap or a list of outstanding features that still need implementing? I haven't looked through the crate much yet.

**Comment by kczimm** [comment]
I see the example working now with the ShapesDemo you suggested. Thanks!

**Comment by jhelovuo** [comment]
> Thanks for getting back so quickly. I tried running two instances of the example and both didn't have any output. I'll try running another implementation as you suggest to test it out.
> 
> I don't know where to help. Is there an area in particular that needs work? Is there a roadmap or a list of outstanding features that still need implementing? I haven't looked through the crate much yet.

No, there is no explicit list anywhere.

We are still missing many DDS features. One conceptually straightforward one could be implementing data fragmentation, i.e. support for transporting larger samples than can be put in a single UDP packet. The amount of work is nontrivial, though. A starting point in code is in https://github.com/jhelovuo/RustDDS/blob/master/src/dds/reader.rs#L533 the lower levels are untested and upper level handling of fragments missing.
