### ISSUE TITLE
[question] default receiver list populated with invalid addresses

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#117]
https://github.com/jhelovuo/RustDDS/blob/474c55a5391a655bf6cb4af8ec225fd341bd9191/src/dds/message_receiver.rs#L74

just hoping for some clarification. is there a reason the default receiver lists are populated with an 'invalid' address, as opposed to an empty `Vec`? is this part of the spec?

**Comment by danieleades** [comment]
while i'm at, where should i be pushing pull requests right now? `master` or `0.5`? what's the plan there?

**Comment by jhelovuo** [comment]
> while i'm at, where should i be pushing pull requests right now? `master` or `0.5`? what's the plan there?

Please use master. Branch 0.5 is used to distinguish between 0.4 and 0.5.

**Comment by jhelovuo** [comment]
> just hoping for some clarification. is there a reason the default receiver lists are populated with an 'invalid' address, as opposed to an empty `Vec`? is this part of the spec?

Yes. RTPS spec "Table 8.17 - Initial State of the Receiver" explicitly says so.
