### ISSUE TITLE
inconsistent use of 'depth' types

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#149]
the QOS 'history depth' property is stored in most places as an `Option<i32>`. It seems that usually `Some(..)` means a finite depth, and `None` means 'keep all'. It's clear though what a negative number would mean....

However there are places where `depth > 0` means a finite depth, and `depth <= 0` means 'keep all' (for example in the 'shapes' demo).

what are the intended semantics? Can this be changed to use an unsigned type? (I would suggest `Option<usize>`)

**Comment by jhelovuo** [comment]
> the QOS 'history depth' property is stored in most places as an `Option<i32>`. It seems that usually `Some(..)` means a finite depth, and `None` means 'keep all'. It's clear though what a negative number would mean....

Your interpretation is correct. `Some(negative)` has no reasonable interpretation.

I think `i32` was originally chosen, because the DDS specification (v1.4 Section 2.3.3 `struct HistoryQosPolicy`) uses `long`.




> However there are places where `depth > 0` means a finite depth, and `depth <= 0` means 'keep all' (for example in the 'shapes' demo).

I think is only applies to textual command-line arguments and is not relevant here.

> what are the intended semantics? Can this be changed to use an unsigned type? (I would suggest `Option<usize>`)

Yes, it can.

**Comment by danieleades** [comment]
ok cool, will take a look. I'm guessing it's going to be non-trivial to do this without breaking the serialisation...

**Comment by jhelovuo** [comment]
That's right. Provided that you take care that history depth is always serialized as 32-bit integer, even when `usize` is 64-bit, then the rest of the changes should be quite straightforward.
