### ISSUE TITLE
Clippy run on GitHub is failing

### ISSUE THREAD

**Issue by jhelovuo** [jhelovuo/RustDDS#153]
Running Clippy fails and it says `Resource not accessible by integration`. 

What resource is missing here? Can it be caused by clippy having read-only access to the repository?

@danieleades , maybe you have some insight on this?

**Comment by danieleades** [comment]
there's this issue here - https://github.com/actions-rs/clippy-check/issues/2

due to security restrictions, the `clippy-check` action fails to generate code annotations if the workflow is run on a PR originating from a fork. Although I would imagine that shouldn't apply to your PRs?

**Comment by jhelovuo** [comment]
It does seem to apply to me too. Can you configure Clippy so that it does not require write access?

It sounds like a bad idea to give write permissions to Clippy or any CI tool, if they can be triggered by a PR submitted by anyone.

**Comment by danieleades** [comment]
> It does seem to apply to me too. Can you configure Clippy so that it does not require write access?
> 
> It sounds like a bad idea to give write permissions to Clippy or any CI tool, if they can be triggered by a PR submitted by anyone.

they can't be triggered by anyone, hence the action fails on that last step if it's coming from a fork. As for why it's failing for *you*, that's a mystery...

**Comment by jhelovuo** [comment]
Re-enabled write access for now.
