### ISSUE TITLE
Implement get_matched_subscriptions() call in DataWriter

### ISSUE THREAD

**Issue by jhelovuo** [jhelovuo/RustDDS#16]

**Comment by samcarey** [comment]
I need this. Specifically, I need to know whether the number of matched subscribers is greater than zero.

Would this be a pretty big effort?

**Comment by jhelovuo** [comment]
This (or equivalent) is implemented in current `master` branch as [`DataWriterStatus`](https://docs.rs/rustdds/0.8.6/rustdds/dds/with_key/struct.DataWriter.html#method.as_async_event_stream). It gives updates as matches appear or disappear.
