### ISSUE TITLE
remove `#[allow(dead_code)]`

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#163]
Where does this code-base need to get to before `#[allow(dead_code)]` can be removed? It's a little hard to estimate, but i think there's at least several hundred lines of code which both never gets called and isn't publicly exported. I guess a lot of this has been added speculatively, in case it's needed later. So one hand it would be a shame to lose all that logic, but on the other hand it's extra noise/maintenance burden that isn't currently adding any value.

what do you think?

**Comment by danieleades** [comment]
i would add that removing this lint is going to be non-trivial. I would suggest doing it incrementally (module by module)

**Comment by jhelovuo** [comment]
Placeholders for things that are in the DDS/RTPS specs do add value, as they are design sketches.

Such places should be marked with `#[allow(dead_code)]` and some comment indicating it is a placeholder for X, preferably with reference to X in the spec.

Really dead code should be just removed.

**Comment by danieleades** [comment]
i started looking at this, but i think you might be in a better position than me to know which code is dead, and which is a placeholder worth keeping

**Comment by jhelovuo** [comment]
Some fixed, see PR #165 . 

Can you identify functions that should be marked as `#cfg(test)` , i.e. used in unit test cases only?

**Comment by danieleades** [comment]
> Can you identify functions that should be marked as `#cfg(test)` , i.e. used in unit test cases only?

i think there's a low-tech way. remove a function that the the `dead_code` marks, then run `cargo check --tests`. if that fails, then the function is unused *except* for the tests. I haven't tested this approach

**Comment by jhelovuo** [comment]
#165 fixes this
