### ISSUE TITLE
Can 2 different nodes be publishing/subscribing to the same topic?

### ISSUE THREAD

**Issue by fgadaleta** [jhelovuo/RustDDS#200]

**Comment by jhelovuo** [comment]
Yes. This is basic functionality of DDS. Of course, all the nodes must agree on the topic type and QoS parameters.

You can try the following:
`$ cargo run --example=shapes_demo -- -S -t Square -P -c GREEN`

and in another computer/terminal:

`$ cargo run --example=shapes_demo -- -t Square -P -c YELLOW`

You should see the first node receiving both GREEN and YELLOW shapes.

**Comment by fgadaleta** [comment]
Yeah that works (on local machine - still have to try on remote machines too).
What i am also trying is to publish/subscribe from another implementation (cyclone and RustDDS). So far I get a `SubscriptionMatched` to the right topic, but I cannot get messages yet.
 What I don't understand of that shapes_demo is the events iteration and matching on tokens STOP_PROGRAM, READER_READY, READER_STATUS_READY, WRITER_STATUS_READY
 When i use a publisher from another implementation (cyclone), it seems it only matches event READER_STATUS_READY

**Comment by fgadaleta** [comment]
I confirm that also works on different machines in the same network. 
In case a Reliability QoS metric is active, is there an acknack message sent upon receipt?
