### ISSUE TITLE
Example of nodes at different addresses (in the same network)

### ISSUE THREAD

**Issue by fgadaleta** [jhelovuo/RustDDS#201]
It would be very helpful to have such an example in which two (or more) nodes exchange messages over a network.
Also an example of the discovery mechanism would be great to have.

**Comment by jhelovuo** [comment]
What do you mean by an example?

If you are looking for an example program, you can use the `shapes_demo` included in RustDDS sources. It also (implicitly) uses Discovery.

Or do you mean some other type of example, such as a diagram or a video tutorial?
