### ISSUE TITLE
Implement `event::Source` for `DataReader` and `DataWriter` 

### ISSUE THREAD

**Issue by fgadaleta** [jhelovuo/RustDDS#204]
IMHO this would allow DataReader and DataWriter to be wrapped in `Arc<Mutex<>>`

**Comment by jhelovuo** [comment]
I do not understand this request. There are several unclear points:

* In a previous issue #202 you state that you are already doing this wrapping.
* How does it fail now?
* What makes you think that implementing `mio::event::Source` would help?
* Implementing [`Source`](https://docs.rs/mio/latest/mio/event/trait.Source.html#implementing-eventsource) requires an underlying system file/socket handle. How would you arrange this for a `DataReader`?

**Comment by jhelovuo** [comment]
This seems to be done since Release 0.8.x
