### ISSUE TITLE
一个网卡多个IP地址时，组播监听失败

### ISSUE THREAD

**Issue by lujfsd** [jhelovuo/RustDDS#208]
我有一个网卡，给了两个IP地址，如下图：

![image](https://user-images.githubusercontent.com/3353399/176833743-10b5a8c3-c1ce-4a13-8cd0-151fad2517f8.png)
在第二个网卡(eth0:1)加入组播时，加入失败，返回错误。why not continue?
```
    for multicast_if_ipaddr in get_local_multicast_ip_addrs()? {
      match multicast_if_ipaddr {
        IpAddr::V4(a) => {
          mio_socket.join_multicast_v4(&multicast_group, &a)?;
        }
        IpAddr::V6(_a) => error!("UDPListener::new_multicast() not implemented for IpV6"), // TODO
      }
    }
```

**Comment by jhelovuo** [comment]
Thank you for the patch.

The reason for this error handling behaviour was that probably no-one had ever tested with an interface with multiple addresses.
