### ISSUE TITLE
`speedy::Readable` derive macro is causing Clippy errors

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#228]
The derived `speedy::Readable` implementation has methods that dereference raw pointers. Since in principle, these raw pointers could be *anything*, the methods should be marked as unsafe, but they're not. Clippy doesn't love this.

This needs to be fixed upstream. see - https://github.com/koute/speedy/issues/34

Right now this breaking all of the linting for all of the PRs, which is obscuring other potential issues.

**Comment by jhelovuo** [comment]
Looks like this is fixed.
