### ISSUE TITLE
SequenceNumber wrong decl.

### ISSUE THREAD

**Issue by frehberg** [jhelovuo/RustDDS#231]
This definition is not according to RTPS Spec
```
pub struct SequenceNumber(i64);
```
IDL Definition is as follows. Current decl. may cause bad encoding/decoding and bad wrong CDR alignment. 
```
struct SequenceNumber_t {
long high;
unsigned long low;
};
```

**Comment by jhelovuo** [comment]
Yes, your observation is correct, the data structure definition is not the closest equivalent to IDL definition.

However, this is supposed to be RustDDS internal representation. The external representation is defined in [Readable and Writable](https://github.com/jhelovuo/RustDDS/blob/master/src/structure/sequence_number.rs#L127) implementations for SequenceNumber, which do follow IDL, i.e. treat SequenceNumber as two 32-bit numbers.

Do you have an example where this causes problems?

**Comment by frehberg** [comment]
Ok, I see. In this case it is not an issue, and this ticket can be closed
