### ISSUE TITLE
INFO_TS not getting sent over the wire

### ISSUE THREAD

**Issue by CountryTk** [jhelovuo/RustDDS#234]
After creating a CDR datawriter and writing with it using this

writer.write(message, Some(Timestamp::now())).unwrap();

the INFO_TS submessage is not being sent over the wire.

While I was debugging I can see that the message is being created and appended to the submessage but once it is sent over the wire I can't see it anymore (I'm using wireshark to look at the message)

The wire message that gets created is 146 bytes and under the INFO column it says DATA(w) and HEARTBEAT so 2 of the 3 submessages i would expect to see

Whats the issue here?

EDIT: I also noticed, when sending a message I get a "Event unknown for writer EntityId {[0,0,0] EntityKind:WRITER_WITH_KEY_USER_DEFINED} error

**Comment by jhelovuo** [comment]
Sorry for the slow response, but how was this resolved? Did you get it working?

**Comment by CountryTk** [comment]
Hey, it actually wasn't a library issue. I was most likely inspecting the wrong packets with WireShark and I was using the library incorrectly. I didn't create a reader for my writer. After doing that I got my problem fixed!

**Comment by jhelovuo** [comment]
Ok, good to hear that things are working. It is normal that a Writer does not send any data if there are no Readers matched.
