### ISSUE TITLE
Poorly handled errors when deserializing related_sample_identity

### ISSUE THREAD

**Issue by SelimV** [jhelovuo/RustDDS#285]
The commit 7a4c511 restricts the accepted representation identifiers to `RepresentationIdentifier::PL_CDR_BE` and `RepresentationIdentifier::PL_CDR_LE` in `related_sample_identity` of `inline_qos.rs` by using `pl_cdr_rep_id_to_speedy_d`. This makes the function to return an error for example when the representation identifier is `RepresentationIdentifier::CDR_LE`. The function is called by `Reader::handle_data_msg`, and the error is disregarded by calling `Result::ok`, replacing it with `None`. 

This for example breaks the ros2_service_client example in [jhelovuo/ros2-client](https://github.com/jhelovuo/ros2-client), as the responses have `RepresentationIdentifier::CDR_LE` but require a `related_sample_identity`, and the above error is not printed.

**Comment by SelimV** [comment]
The use of `pl_cdr_rep_id_to_speedy_d` should be checked also elsewhere as closing the server in ros2_service_client or the client in ros2_service_server example cause similar errors for `status_info`. Also, someone should make sure representation identifiers are used correctly and for example commit b478b8cb36bb84aab48d36cdfa06e30fa1eeffac does not cause invalid deserializations when `CDR_LE` etc. are accepted.

In addition, in the ros2_service_client example, restarting the client causes subsequent responses to arrive in 10+ sequence number delay (probably unrelated).

**Comment by jhelovuo** [comment]
Endianness conversion between Serde and Speedy seems legit.
