### ISSUE TITLE
On mac air with m1 chip , find cannot bind the request address

### ISSUE THREAD

**Issue by bigdaronlee163** [jhelovuo/RustDDS#314]
1. run the shape example .         cargo run --example=shapes_demo -- -S -t Square
2.<img width="930" alt="image" src="https://github.com/jhelovuo/RustDDS/assets/49524138/e7c07b03-8a79-4d23-b7fe-804fd6cbc3a4">
3. other example find the same result .

**Comment by jhelovuo** [comment]
I cannot reproduce the issue you are seeing, please provide more details.

Attempt to reproduce:
- Macbook Pro with M1 Pro, MacOS Ventura
- stable Rust toolchain, compiler version 1.74.0, installed via `rustup`
- RustDDS version Release 0.9.0 or latest `master`
- `./cargo run --example=shapes_demo -- -S -t Square` and
- `./cargo run --example=shapes_demo -- -P -t Square`

Result:
Works as expected, no error messages on startup. 

Note: RustDDS currently requires a working, broadcast-capable network interface to run even locally. The example won't work if your Wi-Fi is disabled.
