### ISSUE TITLE
Cross compilation with target x(6_64-pc-windows-gnu fails to link

### ISSUE THREAD

**Issue by ebakoba** [jhelovuo/RustDDS#37]
Problem is exactly the same as described in this issue: [https://github.com/libp2p/rust-libp2p/issues/1447](https://github.com/libp2p/rust-libp2p/issues/1447)

Problem is the dependency crate called `get_if_addrs`, which uses link `#[link(name = "Iphlpapi")]` but not `#[link(name = "iphlpapi")]`

One of the ways to mitigate this problem would be to replace `get_if_addrs` with some other dependency, such as  [if-addrs](https://github.com/messense/if-addrs), which does not have this problem

**Comment by jhelovuo** [comment]
Thanks for pointing this out. I think we have never testes cross-compiling on Linux to windows.

Does the latest master branch commit on github fix it for you?

**Comment by ebakoba** [comment]
I can confirm that this issue has been resolved with the commit [e73aa39](https://github.com/jhelovuo/RustDDS/commit/e73aa39131cd3f1cc479e0f4c42ab8b8b95e58c7#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542)
