### ISSUE TITLE
Implementing multiple keys for struct, keyed topic

### ISSUE THREAD

**Issue by raidv** [jhelovuo/RustDDS#38]
I need to implement a message on keyed topic where multiple (nested) data fields are keys. 
My struct has a field for key that is of another self-defined type that consists of two primitive type numbers. I have implemented the keyed trait for both structs but the problem occurs with implementing `Keyed` trait for multiple fields.
Here is an example

```
#[derive(Serialize, Deserialize)]
pub struct MyMeasurment {
    pub my_measurment_id: MyIdType, // key
    pub my_timestamp: MyTimeType,
    pub my_measurment_value: MyMeasurmentType,
}

impl Keyed for MyMeasurment {
    type K = MyIdType;

    fn get_key(&self) -> Self::K {
        self.my_measurment_id
    }
}

#[derive(Serialize, Deserialize, Clone, Copy)]
pub struct MyIdType {
    pub sender_id: i32,
    pub instance_id: i32,
}

impl Keyed for MyIdType {
    type K = MyIdType;

    fn get_key(&self) -> Self::K {
        MyIdType {
            sender_id: self.sender_id,
            instance_id: self.instance_id,
        }
    }
}
```
Now, when I go to 
```
publisher
    .create_datawriter::<MyMeasurment, CDRSerializerAdapter<MyMeasurment>>(
        self.topic.clone(),
        None,
    )
    .unwrap();
```
I get
```
the trait bound `MyIdType: rustdds::dds::traits::Key` is not satisfied
the trait `rustdds::dds::traits::Key` is not implemented for `MyIdType`rustcE0277
```
The same happens if the Keyed trait implementation is done through `self.clone()`
```
impl Keyed for MyIdType {
    type K = MyIdType;

    fn get_key(&self) -> Self::K {
        self.clone()
    }
}
```
This probably happens because of the recursive reference to `MyIdType` in the Keyed implementation.

When The final Key returned is primitive type then everything works
```
impl Keyed for MyIdType {
    type K = i32;

    fn get_key(&self) -> Self::K {
        self.instance_id,
    }
} 
```
How should one approach to implementing multiple fields of a struct as keys?
In the shapes example there's also only one key of type `String`

**Comment by jhelovuo** [comment]
Your approach is essentially correct, but there seems to be a slight misunderstanding of concepts:

* `MyMeasurment ` needs to implement `Keyed` as you have done, but
* `MyIdType` needs to implement `Key` instead, because it is the key itself, not something that is indexed by a key. `Keyed` is not needed here.

so
```
#[derive(Serialize, Deserialize, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct MyIdType {
    pub sender_id: i32,
    pub instance_id: i32,
}

impl Key for MyIdType {}
```

**Comment by raidv** [comment]
Thank you, this seemed to be the case. 
Working now
