### ISSUE TITLE
MSRV

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#46]
are you targeting a minimum compiler version?

looks like the current MSRV is `1.48.0`

**Comment by jhelovuo** [comment]
No.

Do you have any suggestions what the minimum supported version should be?

**Comment by danieleades** [comment]
> No.
> 
> Do you have any suggestions what the minimum supported version should be?

i don't think there's any need to restrict the MSRV in any way, especially while this is being actively developed. It's more a case of tracking the MSRV so that changes to the MSRV can be tracked as a semver jump.

There's no universally accepted convention, but one strategy is to treat a MSRV increase as a patch change pre-1.0.0 and as a minor change after 1.0.0 is release

i use [cargo-msrv](https://github.com/foresterre/cargo-msrv) to determine the MSRV, and then a CI target to check that the project builds using that compiler. Then any time i add code or change dependencies which forces the MSRV to increase, the CI will catch that and I can increment the package version.

Maybe that's overkill for this repo, i guess that's up to you to decide.
