### ISSUE TITLE
wrong 'self' convention

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#80]
there's a number of locations that the wrong 'self' convention is used.

there's a reference here - https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention

for example, the `Key` trait has the method `fn into_hash_key(&self) -> KeyHash;`

in order to follow convention, this should *either* move and consume `self` (ie. `fn into_hash_key(self) -> KeyHash`) or use a different name, such as `fn as_hash_key(&self) -> KeyHash` or simply `fn hash_key(&self) -> KeyHash`

similarly for `KeyHash::into_cdr_bytes`, `Timestamp::to_ticks`, and a few others

**Comment by danieleades** [comment]
will need a little bit of input before I can make progress on this one

**Comment by jhelovuo** [comment]
In order to follow convention, `into_hash_key` should be renamed as you suggest. `Key` can potentially be large, and should be read-only here, passing by reference is correct.

`into_cdr_bytes` should probably consume `self`, since `KeyHash` is `Copy`.

**Comment by jhelovuo** [comment]
This seems done in 0.5 branch (current master).
