### ISSUE TITLE
Implement find_topic() in DomainParticipant

### ISSUE THREAD

**Issue by jhelovuo** [jhelovuo/RustDDS#9]
src/dds/participant.rs

**Comment by lordisma** [comment]
Hi,

I would love to contribute to the repo. So if there is no problem with that I could try to solve this issue.

@jhelovuo

**Comment by jhelovuo** [comment]
No problem, please go ahead. Do you need advice with this?

**Comment by lordisma** [comment]
Yes, any kind of suggestions always are welcome

**Comment by jhelovuo** [comment]
The find_topic() operation should not need any network activity of its own. The simplest algorithm that pops to my mind is:

1. Check if the requested topic is already in the DiscoveryDB. If yes, return that.
2. If not, wait for the given timeout duration, and check DiscoveryDB again. Return success or failure based on what was found.

This can be further refined by setting up a poll to stop waiting immediately when the topic is entered into DiscoveryDB, but that could a bit more complicated.

If you start developing this, be sure to start from a working commit. The latest ones in master branch are marked WiP and likely do not work. I suggest using e.g. version tagged 0.2.2. A slightly better Shapes test program is in https://github.com/jhelovuo/dds-rtps .

Other vendors' test binaries are in https://github.com/omg-dds/dds-rtps/releases . At least RTI, OpenDDS, and TOC should work against RustDDS 0.2.2.

**Comment by kczimm** [comment]
I was attempting to implement this but got confused with the DiscoveryDB. How do I return a Topic when what I find in the DiscoeryDB is DiscoveredTopicData? What is the relationship between the two?

Sorry in advance if this is a silly question.

**Comment by jhelovuo** [comment]
Not a silly question. In fact, you have discovered an essential part of this task.

DiscoveryDB stores what is received from the wire from other DDS participants. It is stored as `DiscoveredTopicData,` because that is what we receive, almost verbatim.

To serve the DDS API, we need the `Topic` struct.

A major part of this issue is implementing the transformation from `DiscoveredTopicData` to `Topic`. You could approach this by going through the contents of `Topic` and finding a way to produce each of those from a `DiscoveredTopicData`.

**Comment by jhelovuo** [comment]
Implemented in https://github.com/jhelovuo/RustDDS/commit/78d11ccd8f9457db5ce0aa4880e30bf2eb724314
